@startuml
class Deportivo extends Coche {
  + caballosPotencia: int
  + Deportivo(matricula: String, marca: String, modelo: String, kilometraje: int, precio: double, numeroPuertas: int, caballosPotencia: int)
  + getCaballosPotencia(): int
  + setCaballosPotencia(caballosPotencia: int): void
}
@enduml
