@startuml
class Deportivo extends Coche {
  + aceleracion0a100: double
  + potenciaCV: int
  + tieneModoPista: boolean
  + Deportivo(matricula: String, marca: String, modelo: String, kilometraje: int, precio: double, numeroPuertas: int, aceleracion0a100: double, potenciaCV: int, tieneModoPista: boolean)
  + getAceleracion0a100(): double
  + setAceleracion0a100(aceleracion0a100: double): void
  + getPotenciaCV(): int
  + setPotenciaCV(potenciaCV: int): void
  + getTieneModoPista(): boolean
  + setTieneModoPista(tieneModoPista: boolean): void
}
@enduml