@startuml
class Moto extends Vehiculo implements Valorable {
  + cilindrada: int
  + peso: int
  + alturaAsiento: double
  + tipoTransmision: TipoTransmision <<enum>>
  + Moto(matricula: String, marca: String, modelo: String, kilometraje: int, precio: double, cilindrada: int, peso: int, alturaAsiento: double, tipoTransmision: TipoTransmision)
  + getCilindrada(): int
  + setCilindrada(cilindrada: int): void
  + getPeso(): int
  + setPeso(peso: int): void
  + getAlturaAsiento(): double
  + setAlturaAsiento(alturaAsiento: double): void
  + getTipoMoto(): TipoMoto
  + setTipoMoto(tipoMoto: TipoMoto): void
  + getTipoTransmision(): TipoTransmision
  + setTipoTransmision(tipoTransmision: TipoTransmision): void
  + calcularDepreciacion(): double
}

enum TipoTransmision {
  MANUAL
  AUTOMATICA
}
@enduml
