@startuml
class SUV extends Coche {
  + capacidadOffroad: boolean
  + alturaLibreSuelo: double
  + SUV(matricula: String, marca: String, modelo: String, kilometraje: int, precio: double, numeroPuertas: int, traccion4x4: boolean)
  + getCapacidadOffroad(): boolean
  + setCapacidadOffroad(capacidadOffroad: boolean): void
  + getAlturaLibreSuelo(): double
  + setAlturaLibreSuelo(alturaLibreSuelo: double): void
}
@enduml
