@startuml
abstract class Vehiculo {
  + matricula: String
  + marca: String
  + modelo: String
  + kilometraje: int
  + precio: double
  + propietario: Persona [0..1]
  + estado: Estado
  + Vehiculo(matricula: String, marca: String, modelo: String, kilometraje: int, precio: double, estado: Estado)
  + getMatricula(): String
  + setMatricula(matricula: String): void
  + getMarca(): String
  + setMarca(marca: String): void
  + getModelo(): String
  + setModelo(modelo: String): void
  + getKilometraje(): int
  + setKilometraje(kilometraje: int): void
  + getPrecio(): double
  + setPrecio(precio: double): void
  + getPropietario(): Persona
  + setPropietario(propietario: Persona): void
  + getEstado(): Estado
  + setEstado(estado: Estado): void
  + calcularDepreciacion(): double <<abstract>>
}

enum Estado {
  DISPONIBLE
  VENDIDO
}
@enduml
